name: block_fake_login
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^8.1.4
  authentication_repository:
    path: packages/authentication_repository
  equatable: ^2.0.7
  user_repository:
    path: packages/user_repository
  flutter_bloc: ^8.1.6
  formz: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
